name: Build DOCS

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 设置 Bun
        uses: oven-sh/setup-bun@db6bcf6eb8d88a8aa03265b887ec7bd84d64cd68 # v2.1.1
        with:
          bun-version: 'latest'

      - name: 构建 Docs
        run: |
          bun install
          bun run build

      - name: 上传构建产物
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: puniyu-docs
          path: docs/.vuepress/dist